propertiezsite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog-list'),
    path('<slug:slug>/', views.blog_detail, name='blog-detail'),
]

propertiezsite/agents/models.py
from django.db import models

# Create your models here.
class Integration(models.Model):
    # Name of integration eg: PropData / PropCtrl 
    name = models.CharField(max_length=100)
    # Whether the integration is enabled
    enabled = models.BooleanField(default=False)
    # Agent integration details
    api_key = models.CharField(null=True, blank=True, max_length=255)
    agent_id = models.CharField(null=True, blank=True, max_length=50)
    branch_id = models.CharField(null=True, blank=True, max_length=50)
    
    # Integration settings TODO
    # feed_leads = models.BooleanField(null=True, blank=True, default=False)
    # feed_listings = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self) -> str:
        return f"{self.name}: {self.enabled}"
    
def agency_image_upload_to(instance, filename):
    return f"agent_images/agencies/{instance.name}/{filename}"

class Agency(models.Model):
    name = models.CharField(null=False, blank=False, max_length=50)
    branch = models.CharField(null=False, blank=False, max_length=50)
    image = models.ImageField(upload_to=agency_image_upload_to, null=True, blank=True, default=None)
    
    def __str__(self) -> str:
        return f"{self.name}, {self.branch}"
    
    class Meta:
        verbose_name_plural = "Agencies"


def agent_image_upload_to(instance, filename):
    return f"agent_images/agents/{instance.first_name}_{instance.last_name}/{filename}"


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Agent(models.Model):
    # Personal details
    first_name = models.CharField(null=False, blank=False, max_length=50)
    last_name = models.CharField(null=False, blank=False, max_length=50)
    email = models.EmailField(null=False, blank=False, unique=True)
    contact_number = models.CharField(null=False, blank=False, unique=True, max_length=15) 
    ffc_id = models.CharField(null=False, blank=False, unique=True, max_length=20)

    publish_agent = models.BooleanField(default=True)
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=agent_image_upload_to, null=True, blank=True, default=None)

    tags = models.ManyToManyField(Tag, related_name='agents', blank=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

propertiezsite/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core import validators
from agents.models import Agent


# Create your models here.
class PropDataIntegration(models.Model):
    agent_id = models.PositiveIntegerField(null=False, blank=False)
    branch_id = models.PositiveIntegerField(null=False, blank=False)
    location_id = models.PositiveIntegerField(null=False, blank=False)
    area_id = models.PositiveIntegerField(null=False, blank=False)


def listing_image_upload_to(instance, filename):
    # Construct the upload path based on the listing ID
    if isinstance(instance, ResidentialListing):
        listing = instance
    elif isinstance(instance, ListingImage):
        listing = instance.residential_listing
    else:
        return 'listing_images/unknown/'
    "media/listing_images/123_StreetName_SurburbName_AreaName/sample-1.jpg"
    listing_folder = f"{listing.street_number}_{listing.street_name}_{listing.suburb}_{listing.area}"
    return f'listing_images/{listing_folder}/{filename}'


class ResidentialListing(models.Model):
    """Model for Residential Listings."""
    STATUSES = [
        ("Active", "Active"), ("Pending", "Pending"), ("Rented", "Rented"),
        ("Sold", "Sold"), ("Archived", "Archived"), ("Valuation", "Valuation")
    ]
    LISTING_TYPES = [
        ("For Sale", "For Sale"), ("To Let", "To Let")
    ]
    PROPERTY_TYPES = [
        ("Apartment Block", "Apartment Block"),
        ("Apartment", "Apartment"),
        ("Bed & Breakfast", "Bed & Breakfast"),
        ("Building", "Building"),
        ("Bungalow", "Bungalow"),
        ("Club", "Club"),
        ("Cluster", "Cluster"),
        ("Commercial", "Commercial"),
        ("Compound", "Compound"), 
        ("Detached", "Detached"),
        ("Duet", "Duet"),
        ("Duplex", "Duplex"), 
        ("Equestrian Property", "Equestrian Property"),
        ("Farm", "Farm"), 
        ("Flat", "Flat"),
        ("Freehold", "Freehold"),
        ("Freestanding", "Freestanding"),
        ("Full Floor", "Full Floor"),
        ("Garden Cottage", "Garden Cottage"),
        ("Gated Estate", "Gated Estate"),
        ("Golf Estate", "Golf Estate"),
        ("Guest House", "Guest House"),
        ("Half Floor", "Half Floor"),
        ("Hotel Room", "Hotel Room"),
        ("Hotel", "Hotel"),
        ("House", "House"),
        ("Industrial", "Industrial"),
        ("Labour Camp", "Labour Camp"),
        ("Leaseback", "Leaseback"),
        ("Lodge", "Lodge"),
        ("Maisonette", "Maisonette"),
        ("Office", "Office"),
        ("Package Home", "Package Home"),
        ("Penthouse", "Penthouse"),
        ("Retirement Unit", "Retirement Unit"),
        ("Room", "Room"),
        ("Sectional Title", "Sectional Title"),
        ("Semi Detached", "Semi Detached"),
        ("Simplex", "Simplex"),
        ("Small Holding", "Small Holding"),
        ("Studio Apartment", "Studio Apartment"),
        ("Townhouse", "Townhouse"),
        ("Vacant Land", "Vacant Land"),
        ("Villa", "Villa"),
        ("Warehouse", "Warehouse")
    ]
    FLOOR_SIZE_MEASUREMENT_TYPE = [
        ("Square Metres", "Square Metres"), ("Square Feet", "Square Feet")
    ]
    LAND_SIZE_MEASUREMENT_TYPE = [
        ("Square Metres", "Square Metres"), ("Hectares", "Hectares"),
        ("Square Feet", "Square Feet"), ("Acres", "Acres")
    ]
    PROVINCES = [
        ("Eastern Cape", "Eastern Cape"), ("Free State", "Free State"),
        ("Gauteng", "Gauteng"), ("KwaZulu-Natal", "KwaZulu-Natal"),
        ("Limpopo", "Limpopo"), ("Mpumalanga", "Mpumalanga"),
        ("Northern Cape", "Northern Cape"), ("North West", "North West"),
        ("Western Cape", "Western Cape")
    ]
    model = "Residential"
    
    # Property Details
    description = models.TextField(null=True, blank=False)
    status = models.CharField(null=False, blank=False, choices=STATUSES, max_length=20)
    price = models.DecimalField(null=True, blank=False, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    listing_type = models.CharField(null=False, blank=False, choices=LISTING_TYPES, max_length=20)
    property_type = models.CharField(null=False, blank=False, choices=PROPERTY_TYPES, max_length=50)
    # Area
    floor_size = models.DecimalField(null=True, blank=True, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    floor_size_measurement_type = models.CharField(null=True, blank=True, choices=FLOOR_SIZE_MEASUREMENT_TYPE, max_length=20)
    land_size = models.DecimalField(null=True, blank=True, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    land_size_measurement_type = models.CharField(null=True, blank=True, choices=LAND_SIZE_MEASUREMENT_TYPE, max_length=20)
    # Agent
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    
    # Location
    street_number = models.CharField(null=True, blank=False, max_length=10)
    street_name = models.CharField(null=True, blank=False, max_length=100)
    publish_street_address = models.BooleanField(default=True)
    suburb = models.CharField(null=True, blank=True, max_length=100)
    area = models.CharField(null=True, blank=True, max_length=100)
    city = models.CharField(null=True, blank=False, max_length=100)
    province = models.CharField(null=True, blank=False, choices=PROVINCES, max_length=100)
    post_code = models.PositiveIntegerField(null=True, blank=True)

    # Rooms
    bedrooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    bathrooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    studies = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6)
    lounges = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    dining_rooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    garages = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    carports = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6)
    
    # Images
    main_image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)
    # Metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)

    """
    deleted: nullable datetime yyyy-mm-ddThh:mm:ss.SSSZ

    """
    

    def __str__(self):
        """String representation of a Residential Listing."""
        locations = []
        if self.suburb:
            locations.append(self.suburb)
        if self.area:
            locations.append(self.area)
        if self.city:
            locations.append(self.city)
        if self.province:
            locations.append(self.province)
        location = ", ".join(locations)

        bedrooms = ""
        if self.bedrooms:
            bedrooms += str(self.bedrooms.normalize()) + " Bedroom "
        return bedrooms + self.property_type + " " + self.listing_type + " in " + location


class ListingImage(models.Model):
    """Model for additional listing images"""
    residential_listing = models.ForeignKey(ResidentialListing, on_delete=models.CASCADE, default=None, related_name="listing_images")
    image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)

    def __str__(self):
        return self.image.name
    

class ListingFloorplan(models.Model):
    """Model for listing floorplans"""
    image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)


class ListingEnquiry(models.Model):
    """Model for Listing Enquiries."""
    """
    Properties fetched from Listing:
    branch_id <- listing.branch
    listing_model <- listing.model
    listing type <- listing.listing_type:
            { "For Sale": "Buyer",
              "To Let": "Tenant" }
    agent_id <- listing.agent
    areas <- ADD listing.area
    suburbs <- ADD listing.suburb
    property_type <- listing.property_type
    property_types <- ADD listing.property_type
    bedrooms <- listing.bedrooms
    bathrooms <- listing.bathrooms
    garages <- listing.garages
    carports <- listing.carports
    asking_price <- listing.price
    property_address <- listing.street_number + " " + listing.street_name
    property_description <- listing.description
    """
    # Visible Fields
    full_name = models.CharField(null=False, blank=False, max_length=100)
    email = models.EmailField(null=False, blank=False)
    cell_number = models.CharField(null=True, blank=True, max_length=10)
    message = models.TextField(null=True, blank=True, default="Hi, I'm interested in learning more about this property.")
    
    # Propdata stuff
    propdata_id = models.BigIntegerField(null=True, blank=True)
    source = models.CharField(null=False, blank=False, default="Propertiez.co.za", max_length=30)
    source_ref = models.CharField(blank=False, default="e36ef6e1-be37-44ca-94d1-3308b7905b8d", max_length=100)
    source_description = models.CharField(null=False, blank=True, default="Portal", max_length=100)
    hubspotutk = models.CharField(null=True, blank=True, max_length=100)
    
    # Agent, Branch, Listing details
    # branch_id: int, required
    # agent_id: int, nullable
    listing = models.ForeignKey(ResidentialListing, null=False, blank=False, on_delete=models.CASCADE)
    asking_price = models.PositiveIntegerField(null=True, blank=True)
    zoning = models.CharField(max_length=50, blank=True)

propertiezsite/pages/templates/about.html
<!--
About Page:

Providing information about the website's mission, history, team, and values.

This page could also include details about the website's goals and objectives.
-->

{% extends 'base.html' %}

{% block title %}
About Us
{% endblock %}

{% block og-title %}About Us{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}
    <!-- Your main content here -->

<h1>Welcome to Propertiez.co.za</h1>
<h2>Your Premier Destination for Real Estate Solutions</h2>

<p>At Propertiez.co.za, we are more than just a property listing website – we're your trusted partner in navigating the dynamic landscape of South African real estate. Our mission is to empower individuals and families to find their perfect home or investment property, while providing unparalleled support and guidance every step of the way.</p>

<h2>Our History</h2>

<p>Established in 2024, Propertiez.co.za is a fresh and dynamic addition to the South African real estate landscape. Born out of a passion for innovation and a vision for modernizing the property market, we are proud to embark on this exciting journey to redefine the way people buy, sell, and rent properties in South Africa.</p>

<p>From humble beginnings to our current status as a burgeoning startup, we are fueled by a relentless drive to challenge the status quo and revolutionize the real estate industry. Every decision, every innovation, and every interaction is driven by our commitment to providing unparalleled value and service to our users.</p>

<p>As we write the first chapter of our story, we invite you to be a part of this journey. Together, let's create a brighter future for real estate in South Africa, one property at a time.</p>

<h2>Our Values</h2>

<p>At the heart of Propertiez.co.za are our core values, which guide everything we do:</p>

<ul>
    <li><strong>Integrity:</strong> We operate with honesty, transparency, and professionalism in all our interactions.</li>
    <li><strong>Customer-Centricity:</strong> Your needs are our priority, and we are committed to delivering personalized solutions tailored to your unique requirements.</li>
    <li><strong>Innovation:</strong> We embrace change and continuously seek new ways to enhance the real estate experience through technology and innovation.</li>
    <li><strong>Community:</strong> We believe in building strong, lasting relationships with our clients, partners, and the communities we serve.</li>
    <li><strong>Excellence:</strong> We strive for excellence in everything we do, setting the highest standards for ourselves and our services.</li>
</ul>

<h2>Our Goals</h2>

<p>At Propertiez.co.za, our goals are aligned with your aspirations:</p>

<ul>
    <li>To simplify the property search process and provide users with a seamless, user-friendly platform for finding their dream home or investment opportunity.</li>
    <li>To foster a supportive and collaborative environment where buyers, sellers, renters, and agents can connect, communicate, and transact with confidence.</li>
    <li>To stay at the forefront of industry trends and technological advancements, ensuring that our platform evolves to meet the changing needs of our users.</li>
    <li>To contribute positively to the South African real estate market by promoting ethical practices, responsible investing, and sustainable development.</li>
</ul>

<h2>Join Us on the Journey</h2>

<p>Whether you're a first-time homebuyer, a seasoned investor, or a real estate professional, we invite you to join us on this journey. Together, let's unlock the endless possibilities that the South African real estate market has to offer.</p>

<p><strong>Welcome to Propertiez.co.za – Where Your Property Dreams Come to Life.</strong></p>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/calculators.html
<!--
Bond Calculators Page:

Powered by OOBA

Providing interactive calculators or tools to help users estimate mortgage
payments, loan amounts, interest rates, and other financial metrics related to
home loans and bonds.
-->

{% extends 'base.html' %}

{% block title %}
Propertiez.co.za
{% endblock %}

{% block og-type %}{% endblock %}
{% block og-title %}{% endblock %}
{% block og-image %}{% endblock %}
{% block og-description %}{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/contact-form.html
<div class="contact-form">
    <h2>Contact Us</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-field">
            <label for="name" class="form-label">Full Name:</label>
            <input class="form-input" type="text" name="name" id="id_name" required>
        </div>
        <div class="form-field">
            <label for="email" class="form-label">Email:</label>
            <input class="form-input" type="email" name="email" id="id_email" required>
        </div>
        <div class="form-field">
            <label for="subject" class="form-label">Subject:</label>
            <input class="form-input" type="text" name="subject" id="id_subject" required>
        </div>
        <div class="form-field">
            <label for="" class="form-label">Message:</label>
            <textarea class="form-input" name="message" id="id_message" required></textarea>
        </div>
        <input type="submit" value="Send Message" class="form-button">
    </form>
</div>

propertiezsite/pages/templates/contact-us.html
<!--
Contact Us Page:

Offering various methods for users to get in touch with the website's
administrators or support team.

This page could include a contact form, email addresses, phone numbers, office
locations, and social media links.
-->


{% extends 'base.html' %}
{% load static %}

{% block title %}
Contact Us
{% endblock %}

{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/components/pages/contact-us.css' %}">
{% endblock %}

{% block og-title %}Contact Us{% endblock %}


{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

<h1>Get in Touch</h1>

<p>Want to list your property, have a question, feedback, or just want to say hello? We'd love to hear from you! Feel free to reach out to us using the contact information below, and our team will get back to you as soon as possible.</p>

<!-- Contact Form -->
{% block contact-form %}
    {% include 'contact-form.html' %}
{% endblock %}

<!-- Contact Info -->
<div class="contact-info">
    <h2>Contact Information</h2>
    <!-- Email -->
    <p>
        <i class="fa fa-envelope fa-lg"></i>&nbsp;
        <span class="sr-only">Email Address</span>
        <a href="mailto:care@propertiez.co.za">care@propertiez.co.za</a>
    </p>
    <!-- Phone -->
    <p>
        <i class="fa fa-phone fa-lg"></i>&nbsp;
        <span class="sr-only">Phone Number</span>
        +27 87 822 2912
    </p>
    <!-- Whatsapp -->
    <p>
        <i class="fab fa-whatsapp fa-lg"></i>&nbsp;
        <span class="sr-only">Whatsapp</span>
        <a href="https://wa.me/27878222912" target="_blank">Start a chat on Whatsapp</a>
    </p>
    <!-- Address -->
    <p>
        <i class="fa fa-map-marker fa-lg"></i>&nbsp;
        <span class="sr-only">Physical Address</span>
        547 Voortrekker Road, Maitland, Cape Town, South Africa
    </p>
</div>

<!-- Social Media -->
<div class="social-media">
    <h2>Social Media</h2>
    <p>
        <!-- Facebook -->
        <a href="https://www.facebook.com/profile.php?id=61556429130493&mibextid=ZbWKwL" target="_blank" class="no-decoration">
            <i class="fab fa-facebook fa-2x"></i>
            <span class="sr-only">Facebook</span>
        </a>&nbsp;
        <!-- Instagram -->
        <a href="https://www.instagram.com/_propertiez.co.za_worldwide?igsh=MXJhOGZucm11emJraQ==" target="_blank" class="no-decoration">
            <i class="fab fa-instagram fa-2x"></i>
            <span class="sr-only">Instagram</span>
        </a>&nbsp;
        <!-- LinkedIn -->
        <a href="https://www.linkedin.com/company/propertiez-co-za/" target="_blank" class="no-decoration">
            <i class="fab fa-linkedin fa-2x"></i>
            <span class="sr-only">LinkedIn</span>
        </a>&nbsp;
        <!-- TikTok -->
        <a href="https://www.tiktok.com/@propertiez.co.za?_t=8lSqhgPp9QT&_r=1" target="_blank" class="no-decoration">
            <i class="fab fa-tiktok fa-2x"></i>
            <span class="sr-only">TikTok</span>
        </a>&nbsp;
        <!-- Youtube -->
        <a href="https://www.youtube.com/@Propertiez.co_za" target="_blank" class="no-decoration">
            <i class="fab fa-youtube fa-2x"></i>
            <span class="sr-only">Youtube</span>
        </a>
    </p>

</div>

<div class="business-hours">
    <h2>Business Hours</h2>
    <p>Monday - Friday: 9AM - 5PM</p>
</div>

<h2>We're Here to Help</h2>

<p>At Propertiez.co.za, customer satisfaction is our top priority. Whether you're a prospective buyer, seller, renter, or industry partner, we're committed to providing exceptional service and support every step of the way.</p>
<p>Don't hesitate to get in touch – we're here to help you achieve your property goals!</p>

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/cookie-policy.html
{% extends 'base.html' %}

{% block title %}
Cookie Policy
{% endblock %}

{% block og-title %}Cookie Policy{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

<h1>Cookie Policy for Propertiez.co.za</h1>

<section>
    <h2>Purpose</h2>
    <p>The purpose of this policy is to provide comprehensive information about the use of cookies on Propertiez.co.za.</p>
</section>

<section>
    <h2>What are cookies?</h2>
    <p>Cookies are small text files that are stored on your device when you visit a website. They are widely used to make websites work more efficiently and to provide information to the website owners.</p>
</section>

<section>
    <h2>What cookies are used for?</h2>
    <p>There are several types of cookies used on Propertiez.co.za:</p>
    <ul>
        <li><strong>Essential cookies:</strong> Necessary for the operation of the website.</li>
        <li><strong>Functional cookies:</strong> Remember choices you make and provide enhanced features.</li>
        <li><strong>Analytical cookies:</strong> Help us analyze how visitors use our website.</li>
        <li><strong>Advertising cookies:</strong> Used to deliver advertisements relevant to your interests.</li>
    </ul>
</section>

<section>
    <h2>Types of cookies</h2>
    <p>There are two main types of cookies:</p>
    <ul>
        <li><strong>Persistent cookies:</strong> Remain on your device for a specified period.</li>
        <li><strong>Session cookies:</strong> Temporary and deleted when you close your browser.</li>
    </ul>
</section>

<section>
    <h2>Managing cookies</h2>
    <p>You can manage cookies through your browser settings or using cookie management tools. Learn more about <a href="https://www.aboutcookies.org/" target="_blank">managing cookies</a>.</p>
</section>

<section>
    <h2>Links to third-party websites</h2>
    <p>Our website may contain links to third-party websites. We are not responsible for their cookie policies, so please review them before providing any personal information.</p>
</section>

<section>
    <h2>Updates to this policy</h2>
    <p>This Cookie Policy may be updated from time to time to reflect changes in our practices. We will notify you of any significant changes by posting a notice on our website.</p>
</section>

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/faq.html
<!--
FAQ Page:

Addressing frequently asked questions about the website, its services, and the
real estate industry in general.

This page could help users find answers to common inquiries quickly and easily.
-->

{% extends 'base.html' %}

{% block title %}
FAQ
{% endblock %}

{% block og-title %}FAQ{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}


<ul role="list" class="grid">
  <li class="card">
    <h3>Lorem, ipsum.</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
  </li>
  <li class="card">
    <h3>Minus, pariatur?</h3>
    <p>Veritatis optio illum possimus eveniet exercitationem perferendis ad?</p>
  </li>
  <li class="card">
    <h3>Iste, assumenda!</h3>
    <p>Esse minima in maiores similique unde eaque nostrum!</p>
  </li>
  <li class="card">
    <h3>Voluptatem, veritatis!</h3>
    <p>Provident deserunt veniam, debitis alias atque deleniti laboriosam!</p>
  </li>
  <li class="card">
    <h3>Accusamus, magnam.</h3>
    <p>Ipsum accusantium laboriosam, architecto cum dolor odit animi?</p>
  </li>
  <li class="card">
    <h3>Recusandae, placeat.</h3>
    <p>Incidunt, aliquid odit! Eaque nihil mollitia repellat beatae.</p>
  </li>
</ul>


{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/sell.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Sell your property
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/components/divs.css' %}">
{% endblock %}

{% block og-title %}Sell your property{% endblock %}


{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}
<h1 class="dark-green-centered">Sell your property</h1>

<div class="rounded-shadow-border cta">
    <img class="rounded-shadow-border" src="{% static 'media/Images/agent.png' %}" >
    <div>
        <h3 class="dark-green-centered">Sell your property with an agent</h3>
        <p>List your home with a Propertiez.co.za Partner Agent to get local expertise and potentially maximize your sale price.</p>
        <p>Work with a real estate agent for selling support at every step, including prepping, listing, and marketing your home.</p>
        <a href="{% url 'find-agent' %}">
            <button>Find an Agent</button>
        </a>
    </div>
</div>

<div class="rounded-shadow-border cta row-reversed">
    <img class="rounded-shadow-border" src="{% static 'media/Images/owner.png' %}" >
    <div>
        <h3 class="dark-green-centered">Sell your property yourself</h3>
        <p>Deciding to sell your property yourself is referred to as for-sale-by-owner (FSBO).
            The FSBO process is similar to selling with an agent, but without the support an agent can provide.</p>
        <p>In this case, you're responsible for the home prep, marketing, showings, and negotiations.</p>
        <a href="{% url 'fsbo_apply' %}" >
            <button>Sell your property with us</button>
        </a>
    </div>
</div>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/services.html
<!--
Services Page:

Highlighting the various services offered by the website, such as property
listing management, user registration, search functionality, and additional
features like home loans and bond calculators.
-->

{% extends 'base.html' %}

{% block title %}
Our Services
{% endblock %}

{% block og-title %}Our Services{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/pages/templates/terms-of-service.html
<!--
Terms of Service Page:

Outlining the terms and conditions that govern the use of the website,
including legal disclaimers, privacy policies, and user agreements.

This page is important for establishing transparency and setting expectations
for users.
-->

{% extends 'base.html' %}

{% block title %}
Terms of Service
{% endblock %}

{% block og-title %}Terms of Service{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}