propertiezsite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_list, name='blog-list'),
    path('<slug:slug>/', views.blog_detail, name='blog-detail'),
]

propertiezsite/agents/models.py
from django.db import models

# Create your models here.
class Integration(models.Model):
    # Name of integration eg: PropData / PropCtrl 
    name = models.CharField(max_length=100)
    # Whether the integration is enabled
    enabled = models.BooleanField(default=False)
    # Agent integration details
    api_key = models.CharField(null=True, blank=True, max_length=255)
    agent_id = models.CharField(null=True, blank=True, max_length=50)
    branch_id = models.CharField(null=True, blank=True, max_length=50)
    
    # Integration settings TODO
    # feed_leads = models.BooleanField(null=True, blank=True, default=False)
    # feed_listings = models.BooleanField(null=True, blank=True, default=False)

    def __str__(self) -> str:
        return f"{self.name}: {self.enabled}"
    
def agency_image_upload_to(instance, filename):
    return f"agent_images/agencies/{instance.name}/{filename}"

class Agency(models.Model):
    name = models.CharField(null=False, blank=False, max_length=50)
    branch = models.CharField(null=False, blank=False, max_length=50)
    image = models.ImageField(upload_to=agency_image_upload_to, null=True, blank=True, default=None)
    
    def __str__(self) -> str:
        return f"{self.name}, {self.branch}"
    
    class Meta:
        verbose_name_plural = "Agencies"


def agent_image_upload_to(instance, filename):
    return f"agent_images/agents/{instance.first_name}_{instance.last_name}/{filename}"


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Agent(models.Model):
    # Personal details
    first_name = models.CharField(null=False, blank=False, max_length=50)
    last_name = models.CharField(null=False, blank=False, max_length=50)
    email = models.EmailField(null=False, blank=False, unique=True)
    contact_number = models.CharField(null=False, blank=False, unique=True, max_length=15) 
    ffc_id = models.CharField(null=False, blank=False, unique=True, max_length=20)

    publish_agent = models.BooleanField(default=True)
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=agent_image_upload_to, null=True, blank=True, default=None)

    tags = models.ManyToManyField(Tag, related_name='agents', blank=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

propertiezsite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.

def blog_image_upload_to(blogpost, filename):
    return f"blogpost_images/{blogpost.slug}/{filename}"

class BlogPost(models.Model):
    """
    Model representing a blog post.
    """
    STATUSES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=100, null=False, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to=blog_image_upload_to, null=True, blank=True, default=None)

    excerpt = models.TextField(max_length=200, blank=True)

    slug = models.SlugField(max_length=200, unique=True, blank=True)
    tags = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUSES, default='draft')

    created_at = models.DateTimeField(default=timezone.now)
    uploaded_at = models.DateTimeField(auto_now=True)
    

    def save(self, *args, **kwargs):
        """
        Override save method to automatically generete slug from title if not
        provided.
        """
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    def __str__(self):
        return self.title
    

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Blog Post"
        verbose_name_plural = "Blog Posts"

propertiezsite/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core import validators
from agents.models import Agent


# Create your models here.
class PropDataIntegration(models.Model):
    agent_id = models.PositiveIntegerField(null=False, blank=False)
    branch_id = models.PositiveIntegerField(null=False, blank=False)
    location_id = models.PositiveIntegerField(null=False, blank=False)
    area_id = models.PositiveIntegerField(null=False, blank=False)


def listing_image_upload_to(instance, filename):
    # Construct the upload path based on the listing ID
    if isinstance(instance, ResidentialListing):
        listing = instance
    elif isinstance(instance, ListingImage):
        listing = instance.residential_listing
    else:
        return 'listing_images/unknown/'
    "media/listing_images/123_StreetName_SurburbName_AreaName/sample-1.jpg"
    listing_folder = f"{listing.street_number}_{listing.street_name}_{listing.suburb}_{listing.area}"
    return f'listing_images/{listing_folder}/{filename}'


class ResidentialListing(models.Model):
    """Model for Residential Listings."""
    STATUSES = [
        ("Active", "Active"), ("Pending", "Pending"), ("Rented", "Rented"),
        ("Sold", "Sold"), ("Archived", "Archived"), ("Valuation", "Valuation")
    ]
    LISTING_TYPES = [
        ("For Sale", "For Sale"), ("To Let", "To Let")
    ]
    PROPERTY_TYPES = [
        ("Apartment Block", "Apartment Block"),
        ("Apartment", "Apartment"),
        ("Bed & Breakfast", "Bed & Breakfast"),
        ("Building", "Building"),
        ("Bungalow", "Bungalow"),
        ("Club", "Club"),
        ("Cluster", "Cluster"),
        ("Commercial", "Commercial"),
        ("Compound", "Compound"), 
        ("Detached", "Detached"),
        ("Duet", "Duet"),
        ("Duplex", "Duplex"), 
        ("Equestrian Property", "Equestrian Property"),
        ("Farm", "Farm"), 
        ("Flat", "Flat"),
        ("Freehold", "Freehold"),
        ("Freestanding", "Freestanding"),
        ("Full Floor", "Full Floor"),
        ("Garden Cottage", "Garden Cottage"),
        ("Gated Estate", "Gated Estate"),
        ("Golf Estate", "Golf Estate"),
        ("Guest House", "Guest House"),
        ("Half Floor", "Half Floor"),
        ("Hotel Room", "Hotel Room"),
        ("Hotel", "Hotel"),
        ("House", "House"),
        ("Industrial", "Industrial"),
        ("Labour Camp", "Labour Camp"),
        ("Leaseback", "Leaseback"),
        ("Lodge", "Lodge"),
        ("Maisonette", "Maisonette"),
        ("Office", "Office"),
        ("Package Home", "Package Home"),
        ("Penthouse", "Penthouse"),
        ("Retirement Unit", "Retirement Unit"),
        ("Room", "Room"),
        ("Sectional Title", "Sectional Title"),
        ("Semi Detached", "Semi Detached"),
        ("Simplex", "Simplex"),
        ("Small Holding", "Small Holding"),
        ("Studio Apartment", "Studio Apartment"),
        ("Townhouse", "Townhouse"),
        ("Vacant Land", "Vacant Land"),
        ("Villa", "Villa"),
        ("Warehouse", "Warehouse")
    ]
    FLOOR_SIZE_MEASUREMENT_TYPE = [
        ("Square Metres", "Square Metres"), ("Square Feet", "Square Feet")
    ]
    LAND_SIZE_MEASUREMENT_TYPE = [
        ("Square Metres", "Square Metres"), ("Hectares", "Hectares"),
        ("Square Feet", "Square Feet"), ("Acres", "Acres")
    ]
    PROVINCES = [
        ("Eastern Cape", "Eastern Cape"), ("Free State", "Free State"),
        ("Gauteng", "Gauteng"), ("KwaZulu-Natal", "KwaZulu-Natal"),
        ("Limpopo", "Limpopo"), ("Mpumalanga", "Mpumalanga"),
        ("Northern Cape", "Northern Cape"), ("North West", "North West"),
        ("Western Cape", "Western Cape")
    ]
    model = "Residential"
    
    # Property Details
    description = models.TextField(null=True, blank=False)
    status = models.CharField(null=False, blank=False, choices=STATUSES, max_length=20)
    price = models.DecimalField(null=True, blank=False, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    listing_type = models.CharField(null=False, blank=False, choices=LISTING_TYPES, max_length=20)
    property_type = models.CharField(null=False, blank=False, choices=PROPERTY_TYPES, max_length=50)
    # Area
    floor_size = models.DecimalField(null=True, blank=True, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    floor_size_measurement_type = models.CharField(null=True, blank=True, choices=FLOOR_SIZE_MEASUREMENT_TYPE, max_length=20)
    land_size = models.DecimalField(null=True, blank=True, decimal_places=2, validators=[MinValueValidator(0)], max_digits=20)
    land_size_measurement_type = models.CharField(null=True, blank=True, choices=LAND_SIZE_MEASUREMENT_TYPE, max_length=20)
    # Agent
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    
    # Location
    street_number = models.CharField(null=True, blank=False, max_length=10)
    street_name = models.CharField(null=True, blank=False, max_length=100)
    publish_street_address = models.BooleanField(default=True)
    suburb = models.CharField(null=True, blank=True, max_length=100)
    area = models.CharField(null=True, blank=True, max_length=100)
    city = models.CharField(null=True, blank=False, max_length=100)
    province = models.CharField(null=True, blank=False, choices=PROVINCES, max_length=100)
    post_code = models.PositiveIntegerField(null=True, blank=True)

    # Rooms
    bedrooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    bathrooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    studies = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6)
    lounges = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    dining_rooms = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    garages = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6
    )
    carports = models.DecimalField(
        null=True, blank=True, decimal_places=1, default=0,
        validators=[MinValueValidator(0)], max_digits=6)
    
    # Images
    main_image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)
    # Metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)

    """
    deleted: nullable datetime yyyy-mm-ddThh:mm:ss.SSSZ

    """
    

    def __str__(self):
        """String representation of a Residential Listing."""
        locations = []
        if self.suburb:
            locations.append(self.suburb)
        if self.area:
            locations.append(self.area)
        if self.city:
            locations.append(self.city)
        if self.province:
            locations.append(self.province)
        location = ", ".join(locations)

        bedrooms = ""
        if self.bedrooms:
            bedrooms += str(self.bedrooms.normalize()) + " Bedroom "
        return bedrooms + self.property_type + " " + self.listing_type + " in " + location


class ListingImage(models.Model):
    """Model for additional listing images"""
    residential_listing = models.ForeignKey(ResidentialListing, on_delete=models.CASCADE, default=None, related_name="listing_images")
    image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)

    def __str__(self):
        return self.image.name
    

class ListingFloorplan(models.Model):
    """Model for listing floorplans"""
    image = models.ImageField(upload_to=listing_image_upload_to, null=True, blank=True)


class ListingEnquiry(models.Model):
    """Model for Listing Enquiries."""
    """
    Properties fetched from Listing:
    branch_id <- listing.branch
    listing_model <- listing.model
    listing type <- listing.listing_type:
            { "For Sale": "Buyer",
              "To Let": "Tenant" }
    agent_id <- listing.agent
    areas <- ADD listing.area
    suburbs <- ADD listing.suburb
    property_type <- listing.property_type
    property_types <- ADD listing.property_type
    bedrooms <- listing.bedrooms
    bathrooms <- listing.bathrooms
    garages <- listing.garages
    carports <- listing.carports
    asking_price <- listing.price
    property_address <- listing.street_number + " " + listing.street_name
    property_description <- listing.description
    """
    # Visible Fields
    full_name = models.CharField(null=False, blank=False, max_length=100)
    email = models.EmailField(null=False, blank=False)
    cell_number = models.CharField(null=True, blank=True, max_length=10)
    message = models.TextField(null=True, blank=True, default="Hi, I'm interested in learning more about this property.")
    
    # Propdata stuff
    propdata_id = models.BigIntegerField(null=True, blank=True)
    source = models.CharField(null=False, blank=False, default="Propertiez.co.za", max_length=30)
    source_ref = models.CharField(blank=False, default="e36ef6e1-be37-44ca-94d1-3308b7905b8d", max_length=100)
    source_description = models.CharField(null=False, blank=True, default="Portal", max_length=100)
    hubspotutk = models.CharField(null=True, blank=True, max_length=100)
    
    # Agent, Branch, Listing details
    # branch_id: int, required
    # agent_id: int, nullable
    listing = models.ForeignKey(ResidentialListing, null=False, blank=False, on_delete=models.CASCADE)
    asking_price = models.PositiveIntegerField(null=True, blank=True)
    zoning = models.CharField(max_length=50, blank=True)

propertiezsite/listings/forms.py
from django import forms
from .models import ResidentialListing, ListingImage, ListingEnquiry


class ListingImageForm(forms.ModelForm):
    class Meta:
        model = ListingImage
        fields = ['image']



class ResidentialListingForm(forms.ModelForm):
    class Meta:
        model = ResidentialListing
        fields = [
            "agent",

            "street_number", "street_name", "publish_street_address",
            "suburb", "area", "city", "province", "post_code",

            "status", "price", "listing_type",
            
            "bedrooms", "bathrooms",
            "studies", "lounges", "dining_rooms",
            "garages", "carports",

            "property_type", "description", 
            "floor_size", "floor_size_measurement_type",
            "land_size", "land_size_measurement_type",

            "main_image"
            ]


class ListingEnquiryForm(forms.ModelForm):
    class Meta:
        model = ListingEnquiry
        fields = [
            "full_name", "email", "cell_number", "is_prequalified", "message",
            "add_to_mailing_list", "consent_information",
            "consent_messages", "consent_calls"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['full_name'].required = True
        self.fields['email'].required = True
        self.fields['consent_information'].required = True
        self.fields['consent_messages'].required = True

propertiezsite/listings/templates/add-listing.html
<!--
Listing Creation Page:

An HTML form page where authorized users (e.g., agents) can add new property
listings to the website.

This page would include fields for entering details about the property, such as
title, description, images, price, location, features, and amenities.
-->

{% extends 'base.html' %}



{% block title %}
Add New Listing
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}
<h1>Add New Listing</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <label for="listing-image">Upload Photos:</label>
    <input type="file" id="listing-image" name="listing-image" accept="image/*" multiple>
    <p></p>
    <input type="submit" value="Add Listing">
</form>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/edit-listing.html
<!--
Listing Edit Page:

Similar to the creation page but for editing existing property listings.

This page would allow authorized users to modify the details of a listing,
including updating images, changing price, editing description, and adjusting
other attributes.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}
<h2>Edit Listing</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <label for="image_formset">Existing Photos:</label>
    {{ image_formset.management_form }}
    {% for image_form in image_formset %}
        {{ image_form.as_p }}
    {% endfor %}

    <label for="listing-image">Upload Photos:</label>
    <input type="file" id="listing-image" name="listing-image" accept="image/*" multiple>
    <p></p>
    <button type="submit">Save Changes</button>
</form>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/enquiry-form.html
<!--
Listing Enquiry Form:

An HTML form page where users can submit enquiries or requests for more
information about a specific property listing.

This page would include fields for the user to input their name, email, phone
number, message, and possibly the listing they're interested in.
-->

<div class="enquiry-form">
    <h3>Contact Agent</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Enquiry Details -->
        <div class="enquiry-form-field">
            <label class="enquiry-form-label" for="full_name">Full Name<span style="color: red;">*</span></label>
            {{ form.full_name }} 
        </div>
        <div class="enquiry-form-field">
            <label class="enquiry-form-label" for="email">Email<span style="color: red;">*</span></label>
            {{ form.email }} 
        </div>
        <div class="enquiry-form-field">
            <label class="enquiry-form-label" for="cell_number">Contact Number</label>
            {{ form.cell_number }} 
        </div>

        <div class="enquiry-form-field">
            <label class="enquiry-form-label" for="message">Message</label>
            <br>
            {{ form.message }} 
        </div>
        <div class="enquiry-form-checkbox">
            <input type="checkbox" name="is_prequalified" id="is_prequalified">
            <label class="enquiry-form-checkbox-label" for="is_prequalified">
                I have pre-qualified for a home loan
            </label>
        </div>
        <p><strong>I consent to:</strong></p>
        <div class="enquiry-form-checkbox">
            <input type="checkbox" name="add_to_mailing_list" id="add_to_mailing_list">
            <label class="enquiry-form-checkbox-label" for="add_to_mailing_list">
                Receiving marketing information from Propertiez.co.za
            </label>
        </div>
        <div class="enquiry-form-checkbox">
            <input type="checkbox" name="consent_information" id="consent_information" required><span style="color: red;">*</span>
            <label class="enquiry-form-checkbox-label" for="consent_information">
                Sharing my details with Propertiez.co.za, the Listing Agent, and third-party property directories
            </label>
        </div>
        <div class="enquiry-form-checkbox">
            <input type="checkbox" name="consent_messages" id="consent_messages" required><span style="color: red;">*</span>
            <label class="enquiry-form-checkbox-label" for="consent_messages">
                Email communication regarding this listing
            </label>
        </div>
        <div class="enquiry-form-checkbox">
            <input type="checkbox" name="consent_calls" id="consent_calls">
            <label class="enquiry-form-checkbox-label" for="consent_calls">
                Telephonic communication regarding this listing
            </label>
        </div>
        <input type="submit" value="Send Enquiry">
    </form>
</div>

propertiezsite/listings/templates/featured-listings.html
<!--
Featured Listings Page:
A page showcasing featured or premium listings that are highlighted for greater
visibility.
This page might display a curated selection of properties with prominent
visuals and detailed descriptions.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/fsbo-application.html
{% extends 'base.html' %}

{% block title %}
List your property
{% endblock %}

{% block og-title %}List your property{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}
<h1 class="dark-green-centered">Property Listing Form</h1>

<form action="" method="post" enctype="multipart/form-data">
    <h3>Property Details</h3>
    <div class="form-field">
        <label for="title" class="form-label">Property Title</label>
        <input class="form-input" type="text" name="title" id="id_title" required>
    </div>
    <div class="form-field">
        <label for="description" class="form-label">Description</label>
        <textarea class="form-input" name="description" id="id_description" required></textarea>
    </div>
    <div class="form-field">
        <label for="price" class="form-label">Price</label>
        <input class="form-input" type="number" name="price" id="id_price" required>
    </div>
    <div class="form-field">
        <label for="location" class="form-label">Location</label>
        <input class="form-input" type="text" name="location" id="id_location" required>
    </div>
    <h3>Owner Details</h3>
    <div class="form-field">
        <label for="name" class="form-label">Full Name</label>
        <input class="form-input" type="text" name="name" id="id_name" required>
    </div>
    <div class="form-field">
        <label for="email" class="form-label">Email Address</label>
        <input class="form-input" type="email" name="email" id="id_email" required>
    </div>
    <div class="form-field">
        <label for="contact" class="form-label">Contact Number</label>
        <input class="form-input" type="tel" name="contact" id="id_contact" required>
    </div>
    {% csrf_token %}
    <input type="submit" value="Submit" class="form-button">
</form>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/get-prequalified.html
{% block get-prequalified %}

<div class="get-prequalified-container">
    <h3>Need to pre-qualify for a home loan?</h3>
    <a href="https://qrco.de/PFCAE" class="prequalify-link">Get Pre-qualified</a>
</div>

{% endblock %}

propertiezsite/listings/templates/listing-categories.html
<!--
Listing Category Pages:

Pages displaying listings categorized by:
    property type (e.g., houses, apartments, condos, land),
    status (for sale, for rent),
    location (cities, provinces),
    or other criteria.

Each category page would list relevant listings with brief summaries and links
to the detailed listing pages.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/listings-map-view.html
<!--
Listing Map View:

Displaying property listings on a map interface, allowing users to visually
browse listings based on their geographic location.

Each listing marker on the map would link to the corresponding listing detail
page.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/manage-listings.html
<!--
Listing Management Dashboard:

If authorized users have access to a dashboard to manage their listings, you'll
need HTML templates for various dashboard views such as listing management,
analytics, and performance metrics.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

propertiezsite/listings/templates/pagination.html
<!-- Pagination -->
<div class="pagination">
    <span class="step-links">
        <!-- Back -->
        {% if listings.has_previous %}
            <!-- First -->
            <a href="?page=1">&laquo;&nbsp;First</a>
            <!-- Previous -->
            <a href="?page={{ listings.previous_page_number }}">Back</a>
        {% endif %}

        <!-- Current Page -->
        <span class="current">
            Page {{ listings.number }}/{{ listings.paginator.num_pages }}
        </span>

        <!-- Forward -->
        {% if listings.has_next %}
            <!-- Next -->
            <a href="?page={{ listings.next_page_number }}">Next</a>
            <!-- Last -->
            <a href="?page={{ listings.paginator.num_pages }}">Last&nbsp;&raquo;</a>
        {% endif %}
    </span>
</div>

propertiezsite/listings/templates/saved-listings.html
<!--
Saved Listings Page:

For registered users who can save listings for later viewing, you'll need an
HTML template for the saved listings page where users can view and manage their
saved properties.
-->

{% extends 'base.html' %}

{% block title %}
Title
{% endblock %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}